site_name: Open edX Deployment
site_dir: build
theme:
  name: material
  custom_dir: theme_overrides
  logo: assets/opencraft-logo.svg
extra_css:
  - assets/opencraft-branding.css
markdown_extensions:
  - toc:
      permalink: true
